services:
  webserver:
    image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}"
    container_name: thang_webserver
    depends_on:
      - db
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
      - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
    environment:
      MOODLE_DOCKER_RUNNING: 1
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
      MOODLE_DOCKER_TIMEOUT_FACTOR: "${MOODLE_DOCKER_TIMEOUT_FACTOR}"
    restart: always
    ports:
      - "${MOODLE_DOCKER_WEB_PORT}:80"
    # command: >
    #   bash -c "
    #   pecl install xdebug &&
    #   docker-php-ext-enable xdebug &&

    #   echo 'xdebug.mode = debug' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&
    #   echo 'xdebug.client_host = docker.internal.host' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&
    #   echo 'xdebug.client_port = 9004' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&
    #   echo 'xdebug.start_with_request = yes' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&
    #   echo 'xdebug.log = /tmp/xdebug.log' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&
    #   echo 'xdebug.discover_client_host = 1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&
    #   echo 'xdebug.idekey=VSCODE' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    extra_hosts:
      - host.docker.internal:host-gateway